server:
  port: 3344
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duanzhaxou/microservicecloud-config.git

management:
 security:
    enabled: false